# Generated by Django 5.1.2 on 2024-10-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='high_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='low_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='close_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='open_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='volume',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='stockdata',
            unique_together={('symbol', 'date')},
        ),
    ]
