# Generated by Django 5.1.2 on 2024-10-23 22:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stockdata_high_price_stockdata_low_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
